[project]
name = "customtube"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "asgiref>=3.10.0",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "uvicorn>=0.38.0",
    "yt-dlp>=2025.11.12",
]
